/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AvailabilityResponse from '../model/AvailabilityResponse';
import CheckAvailability200Response from '../model/CheckAvailability200Response';

/**
* Availability service.
* @module api/AvailabilityApi
* @version 2.0.0
*/
export default class AvailabilityApi {

    /**
    * Constructs a new AvailabilityApi. 
    * @alias module:api/AvailabilityApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the checkAvailability operation.
     * @callback module:api/AvailabilityApi~checkAvailabilityCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CheckAvailability200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check availability (general)
     * General availability check endpoint proxied to main app.
     * @param {String} instructorId 
     * @param {Date} date Date in YYYY-MM-DD format (e.g. 2026-03-25)
     * @param {Number} duration Lesson duration in minutes: 60, 90, or 120
     * @param {Object} opts Optional parameters
     * @param {Object.<String, Object>} [body] 
     * @param {module:api/AvailabilityApi~checkAvailabilityCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CheckAvailability200Response}
     */
    checkAvailability(instructorId, date, duration, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'instructorId' is set
      if (instructorId === undefined || instructorId === null) {
        throw new Error("Missing the required parameter 'instructorId' when calling checkAvailability");
      }
      // verify the required parameter 'date' is set
      if (date === undefined || date === null) {
        throw new Error("Missing the required parameter 'date' when calling checkAvailability");
      }
      // verify the required parameter 'duration' is set
      if (duration === undefined || duration === null) {
        throw new Error("Missing the required parameter 'duration' when calling checkAvailability");
      }

      let pathParams = {
      };
      let queryParams = {
        'instructorId': instructorId,
        'date': date,
        'duration': duration
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CheckAvailability200Response;
      return this.apiClient.callApi(
        '/availability', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAvailableSlots operation.
     * @callback module:api/AvailabilityApi~getAvailableSlotsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AvailabilityResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get available time slots
     * Returns available booking slots for an instructor on a specific date
     * @param {String} instructorId Instructor ID to get slots for
     * @param {Date} date Date in YYYY-MM-DD format (e.g. 2026-03-25)
     * @param {Object} opts Optional parameters
     * @param {Number} [duration] Lesson duration in minutes (e.g. 60)
     * @param {module:api/AvailabilityApi~getAvailableSlotsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AvailabilityResponse}
     */
    getAvailableSlots(instructorId, date, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'instructorId' is set
      if (instructorId === undefined || instructorId === null) {
        throw new Error("Missing the required parameter 'instructorId' when calling getAvailableSlots");
      }
      // verify the required parameter 'date' is set
      if (date === undefined || date === null) {
        throw new Error("Missing the required parameter 'date' when calling getAvailableSlots");
      }

      let pathParams = {
      };
      let queryParams = {
        'instructorId': instructorId,
        'date': date,
        'duration': opts['duration']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AvailabilityResponse;
      return this.apiClient.callApi(
        '/availability/slots', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
