/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CancelBooking200Response from '../model/CancelBooking200Response';
import CancelBookingRequest from '../model/CancelBookingRequest';
import CreateBooking200Response from '../model/CreateBooking200Response';
import CreateBookingRequest from '../model/CreateBookingRequest';
import Error from '../model/Error';
import LookupBookings200Response from '../model/LookupBookings200Response';
import LookupBookings400Response from '../model/LookupBookings400Response';
import RescheduleBooking200Response from '../model/RescheduleBooking200Response';
import RescheduleBookingRequest from '../model/RescheduleBookingRequest';

/**
* Bookings service.
* @module api/BookingsApi
* @version 2.0.0
*/
export default class BookingsApi {

    /**
    * Constructs a new BookingsApi. 
    * @alias module:api/BookingsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the cancelBooking operation.
     * @callback module:api/BookingsApi~cancelBookingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CancelBooking200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cancel a booking (requires verification)
     * Cancel a booking after verifying the requestor's identity via the `X-Verification-Token` header (OTP confirmation).
     * @param {String} id 
     * @param {String} xVerificationToken Short-lived verification token from OTP confirmation
     * @param {Object} opts Optional parameters
     * @param {String} [idempotencyKey] Idempotency key for safely retrying cancel requests
     * @param {module:model/CancelBookingRequest} [body] 
     * @param {module:api/BookingsApi~cancelBookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CancelBooking200Response}
     */
    cancelBooking(id, xVerificationToken, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling cancelBooking");
      }
      // verify the required parameter 'xVerificationToken' is set
      if (xVerificationToken === undefined || xVerificationToken === null) {
        throw new Error("Missing the required parameter 'xVerificationToken' when calling cancelBooking");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Verification-Token': xVerificationToken,
        'Idempotency-Key': opts['idempotencyKey']
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CancelBooking200Response;
      return this.apiClient.callApi(
        '/public/bookings/{id}/cancel', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createBooking operation.
     * @callback module:api/BookingsApi~createBookingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateBooking200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create booking with package
     * Create a new booking or package purchase. IMPORTANT: Backend calculates pricing - AI should NOT send pricing fields. AI only sends: instructor, package type, schedule, and account details.  INSTRUCTOR RESOLUTION: Either `instructorId` or `instructorQuery` must be provided. - `instructorId`: use when you already have the ID from a previous search/recommendations call - `instructorQuery`: use when you only have a name or phone — backend resolves to an ID AI should NEVER ask the caller for an instructor ID directly.  NOTE: Although this path is under `/public`, this endpoint requires Bearer authentication and is intended for trusted service-to-service calls from the hybrid voice service to the main DriveBook API. Present a valid `Authorization: Bearer <token>`.  CONDITIONAL VALIDATION (documented): - Either `instructorId` or `instructorQuery` must be present. - If `packageType` is `CUSTOM`, `hours` is required. - If `bookingType` is `now`, `scheduledBookings` must be supplied and each entry must include `date`, `time`, `duration`, and `pickupLocation`. 
     * @param {module:model/CreateBookingRequest} body 
     * @param {Object} opts Optional parameters
     * @param {String} [idempotencyKey] Idempotency key for safely retrying create booking requests
     * @param {module:api/BookingsApi~createBookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateBooking200Response}
     */
    createBooking(body, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createBooking");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'Idempotency-Key': opts['idempotencyKey']
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateBooking200Response;
      return this.apiClient.callApi(
        '/public/bookings/bulk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the lookupBookings operation.
     * @callback module:api/BookingsApi~lookupBookingsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LookupBookings200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Look up bookings by phone number
     * Find existing bookings when the user provides a phone number. Used for reschedule/cancel flows.
     * @param {String} phone Phone number used on the booking (E.164 recommended)
     * @param {module:api/BookingsApi~lookupBookingsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LookupBookings200Response}
     */
    lookupBookings(phone, callback) {
      let postBody = null;
      // verify the required parameter 'phone' is set
      if (phone === undefined || phone === null) {
        throw new Error("Missing the required parameter 'phone' when calling lookupBookings");
      }

      let pathParams = {
      };
      let queryParams = {
        'phone': phone
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LookupBookings200Response;
      return this.apiClient.callApi(
        '/bookings/lookup', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the rescheduleBooking operation.
     * @callback module:api/BookingsApi~rescheduleBookingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RescheduleBooking200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Reschedule a booking (requires verification)
     * Reschedule a booking after verifying the requestor's identity via the `X-Verification-Token` header (OTP confirmation).
     * @param {String} id 
     * @param {String} xVerificationToken Short-lived verification token from OTP confirmation
     * @param {module:model/RescheduleBookingRequest} body 
     * @param {Object} opts Optional parameters
     * @param {String} [idempotencyKey] Idempotency key for safely retrying reschedule requests
     * @param {module:api/BookingsApi~rescheduleBookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RescheduleBooking200Response}
     */
    rescheduleBooking(id, xVerificationToken, body, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling rescheduleBooking");
      }
      // verify the required parameter 'xVerificationToken' is set
      if (xVerificationToken === undefined || xVerificationToken === null) {
        throw new Error("Missing the required parameter 'xVerificationToken' when calling rescheduleBooking");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling rescheduleBooking");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Verification-Token': xVerificationToken,
        'Idempotency-Key': opts['idempotencyKey']
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RescheduleBooking200Response;
      return this.apiClient.callApi(
        '/public/bookings/{id}/reschedule', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
