/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetInstructorRecommendations200Response from '../model/GetInstructorRecommendations200Response';
import LookupBookings400Response from '../model/LookupBookings400Response';
import SearchInstructorsByLocation200Response from '../model/SearchInstructorsByLocation200Response';

/**
* Instructors service.
* @module api/InstructorsApi
* @version 2.0.0
*/
export default class InstructorsApi {

    /**
    * Constructs a new InstructorsApi. 
    * @alias module:api/InstructorsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getInstructorRecommendations operation.
     * @callback module:api/InstructorsApi~getInstructorRecommendationsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetInstructorRecommendations200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get smart instructor recommendations (AI-POWERED)
     * Returns top instructors ranked by intelligent scoring algorithm. Considers rating, distance, price, and experience. This is the BEST endpoint for AI to use - provides pre-ranked, personalized results. 
     * @param {String} location Pickup location (e.g. Joondalup WA)
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [vehicleType] Preferred vehicle type
     * @param {String} [language] Preferred language (e.g. English)
     * @param {Number} [budget] Maximum hourly rate (e.g. 75)
     * @param {module:model/String} [experienceLevel] 
     * @param {Number} [limit = 3)] Number of recommendations to return (default: 3)
     * @param {module:api/InstructorsApi~getInstructorRecommendationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetInstructorRecommendations200Response}
     */
    getInstructorRecommendations(location, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'location' is set
      if (location === undefined || location === null) {
        throw new Error("Missing the required parameter 'location' when calling getInstructorRecommendations");
      }

      let pathParams = {
      };
      let queryParams = {
        'location': location,
        'vehicleType': opts['vehicleType'],
        'language': opts['language'],
        'budget': opts['budget'],
        'experienceLevel': opts['experienceLevel'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetInstructorRecommendations200Response;
      return this.apiClient.callApi(
        '/instructors/recommendations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchInstructorsByLocation operation.
     * @callback module:api/InstructorsApi~searchInstructorsByLocationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SearchInstructorsByLocation200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search instructors by location or name (PRIMARY ENDPOINT)
     * Find instructors who serve a specific location, sorted by distance and rating. This is the MAIN endpoint for the AI to use when a student provides their pickup location. Also supports ?name= for finding a specific instructor by name. 
     * @param {String} location Pickup location - address, suburb, or postcode (e.g. Joondalup WA)
     * @param {module:api/InstructorsApi~searchInstructorsByLocationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SearchInstructorsByLocation200Response}
     */
    searchInstructorsByLocation(location, callback) {
      let postBody = null;
      // verify the required parameter 'location' is set
      if (location === undefined || location === null) {
        throw new Error("Missing the required parameter 'location' when calling searchInstructorsByLocation");
      }

      let pathParams = {
      };
      let queryParams = {
        'location': location
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SearchInstructorsByLocation200Response;
      return this.apiClient.callApi(
        '/instructors/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
