/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetPackages200Response from '../model/GetPackages200Response';

/**
* Packages service.
* @module api/PackagesApi
* @version 2.0.0
*/
export default class PackagesApi {

    /**
    * Constructs a new PackagesApi. 
    * @alias module:api/PackagesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getPackages operation.
     * @callback module:api/PackagesApi~getPackagesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetPackages200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get available lesson packages
     * Returns available lesson packages with pricing. AI should call this to present package options to students. 
     * @param {String} instructorId Instructor ID to get their specific pricing
     * @param {module:api/PackagesApi~getPackagesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetPackages200Response}
     */
    getPackages(instructorId, callback) {
      let postBody = null;
      // verify the required parameter 'instructorId' is set
      if (instructorId === undefined || instructorId === null) {
        throw new Error("Missing the required parameter 'instructorId' when calling getPackages");
      }

      let pathParams = {
      };
      let queryParams = {
        'instructorId': instructorId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetPackages200Response;
      return this.apiClient.callApi(
        '/packages', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
