/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ConfirmOtp200Response from '../model/ConfirmOtp200Response';
import ConfirmOtpRequest from '../model/ConfirmOtpRequest';
import LookupBookings400Response from '../model/LookupBookings400Response';
import SendOtp200Response from '../model/SendOtp200Response';
import SendOtpRequest from '../model/SendOtpRequest';

/**
* Verifications service.
* @module api/VerificationsApi
* @version 2.0.0
*/
export default class VerificationsApi {

    /**
    * Constructs a new VerificationsApi. 
    * @alias module:api/VerificationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the confirmOtp operation.
     * @callback module:api/VerificationsApi~confirmOtpCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ConfirmOtp200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Confirm OTP and issue verification token
     * Confirm the one-time PIN sent to the user. On success returns a short-lived `verificationToken` which clients must present when performing sensitive actions like cancelling or rescheduling a booking. 
     * @param {module:model/ConfirmOtpRequest} body 
     * @param {module:api/VerificationsApi~confirmOtpCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ConfirmOtp200Response}
     */
    confirmOtp(body, callback) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling confirmOtp");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ConfirmOtp200Response;
      return this.apiClient.callApi(
        '/verifications/otp/confirm', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the sendOtp operation.
     * @callback module:api/VerificationsApi~sendOtpCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SendOtp200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send OTP for identity verification
     * Generate and send a one-time PIN (OTP) to the provided phone or email for actions that require identity verification (reschedule, cancel). Returns a short-lived `verificationId` used to confirm the OTP. Codes expire after 5 minutes, allow up to 3 failed confirmation attempts, require a 60-second resend delay, and are rate-limited to 3 requests per hour. 
     * @param {module:model/SendOtpRequest} body 
     * @param {module:api/VerificationsApi~sendOtpCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SendOtp200Response}
     */
    sendOtp(body, callback) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling sendOtp");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SendOtp200Response;
      return this.apiClient.callApi(
        '/verifications/otp', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
