/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HandleIncomingCallRequest from '../model/HandleIncomingCallRequest';
import HandleVoicemailRequest from '../model/HandleVoicemailRequest';

/**
* Voice service.
* @module api/VoiceApi
* @version 2.0.0
*/
export default class VoiceApi {

    /**
    * Constructs a new VoiceApi. 
    * @alias module:api/VoiceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the handleIncomingCall operation.
     * @callback module:api/VoiceApi~handleIncomingCallCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Handle incoming voice call (Twilio webhook)
     * Twilio webhook endpoint for incoming calls
     * @param {String} xTwilioSignature Signature sent by Twilio (validate to verify source)
     * @param {module:model/HandleIncomingCallRequest} body 
     * @param {module:api/VoiceApi~handleIncomingCallCallback} callback The callback function, accepting three arguments: error, data, response
     */
    handleIncomingCall(xTwilioSignature, body, callback) {
      let postBody = body;
      // verify the required parameter 'xTwilioSignature' is set
      if (xTwilioSignature === undefined || xTwilioSignature === null) {
        throw new Error("Missing the required parameter 'xTwilioSignature' when calling handleIncomingCall");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling handleIncomingCall");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Twilio-Signature': xTwilioSignature
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/voice/incoming', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the handleVoicemail operation.
     * @callback module:api/VoiceApi~handleVoicemailCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Handle voicemail recording (Twilio webhook)
     * Twilio webhook for voicemail callbacks
     * @param {String} xTwilioSignature Signature sent by Twilio (validate to verify source)
     * @param {module:model/HandleVoicemailRequest} body 
     * @param {module:api/VoiceApi~handleVoicemailCallback} callback The callback function, accepting three arguments: error, data, response
     */
    handleVoicemail(xTwilioSignature, body, callback) {
      let postBody = body;
      // verify the required parameter 'xTwilioSignature' is set
      if (xTwilioSignature === undefined || xTwilioSignature === null) {
        throw new Error("Missing the required parameter 'xTwilioSignature' when calling handleVoicemail");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling handleVoicemail");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Twilio-Signature': xTwilioSignature
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/voice/voicemail', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
