/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AvailabilityResponse from './model/AvailabilityResponse';
import AvailabilityResponseSlotsInner from './model/AvailabilityResponseSlotsInner';
import BookingCreated from './model/BookingCreated';
import BookingRequest from './model/BookingRequest';
import BookingStatus from './model/BookingStatus';
import CancelBooking200Response from './model/CancelBooking200Response';
import CancelBookingRequest from './model/CancelBookingRequest';
import CheckAvailability200Response from './model/CheckAvailability200Response';
import CheckAvailability200ResponseSlotsInner from './model/CheckAvailability200ResponseSlotsInner';
import ConfirmOtp200Response from './model/ConfirmOtp200Response';
import ConfirmOtpRequest from './model/ConfirmOtpRequest';
import CreateBooking200Response from './model/CreateBooking200Response';
import CreateBooking200ResponsePricing from './model/CreateBooking200ResponsePricing';
import CreateBookingRequest from './model/CreateBookingRequest';
import CreateBookingRequestScheduledBookingsInner from './model/CreateBookingRequestScheduledBookingsInner';
import Error from './model/Error';
import GetInstructorRecommendations200Response from './model/GetInstructorRecommendations200Response';
import GetInstructorRecommendations200ResponseRecommendationsInner from './model/GetInstructorRecommendations200ResponseRecommendationsInner';
import GetPackages200Response from './model/GetPackages200Response';
import GetPackages200ResponseTestPackage from './model/GetPackages200ResponseTestPackage';
import HandleIncomingCallRequest from './model/HandleIncomingCallRequest';
import HandleVoicemailRequest from './model/HandleVoicemailRequest';
import HealthCheck200Response from './model/HealthCheck200Response';
import Instructor from './model/Instructor';
import InstructorLocation from './model/InstructorLocation';
import LookupBookings200Response from './model/LookupBookings200Response';
import LookupBookings200ResponseBookingsInner from './model/LookupBookings200ResponseBookingsInner';
import LookupBookings200ResponseBookingsInnerInstructor from './model/LookupBookings200ResponseBookingsInnerInstructor';
import LookupBookings400Response from './model/LookupBookings400Response';
import OtpResponse from './model/OtpResponse';
import Package from './model/Package';
import RescheduleBooking200Response from './model/RescheduleBooking200Response';
import RescheduleBookingRequest from './model/RescheduleBookingRequest';
import SearchInstructorsByLocation200Response from './model/SearchInstructorsByLocation200Response';
import SearchInstructorsByLocation200ResponseSearchLocation from './model/SearchInstructorsByLocation200ResponseSearchLocation';
import SendOtp200Response from './model/SendOtp200Response';
import SendOtpRequest from './model/SendOtpRequest';
import ValidateLocation200Response from './model/ValidateLocation200Response';
import ValidateLocation200ResponseComponents from './model/ValidateLocation200ResponseComponents';
import ValidateLocationRequest from './model/ValidateLocationRequest';
import AvailabilityApi from './api/AvailabilityApi';
import BookingsApi from './api/BookingsApi';
import InstructorsApi from './api/InstructorsApi';
import LocationsApi from './api/LocationsApi';
import PackagesApi from './api/PackagesApi';
import SystemApi from './api/SystemApi';
import VerificationsApi from './api/VerificationsApi';
import VoiceApi from './api/VoiceApi';


/**
* API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these &#x60;/api/_*&#x60; endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \&quot;I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\&quot; 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DriveBookVoiceServiceApi = require('index'); // See note below*.
* var xxxSvc = new DriveBookVoiceServiceApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DriveBookVoiceServiceApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DriveBookVoiceServiceApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DriveBookVoiceServiceApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AvailabilityResponse model constructor.
     * @property {module:model/AvailabilityResponse}
     */
    AvailabilityResponse,

    /**
     * The AvailabilityResponseSlotsInner model constructor.
     * @property {module:model/AvailabilityResponseSlotsInner}
     */
    AvailabilityResponseSlotsInner,

    /**
     * The BookingCreated model constructor.
     * @property {module:model/BookingCreated}
     */
    BookingCreated,

    /**
     * The BookingRequest model constructor.
     * @property {module:model/BookingRequest}
     */
    BookingRequest,

    /**
     * The BookingStatus model constructor.
     * @property {module:model/BookingStatus}
     */
    BookingStatus,

    /**
     * The CancelBooking200Response model constructor.
     * @property {module:model/CancelBooking200Response}
     */
    CancelBooking200Response,

    /**
     * The CancelBookingRequest model constructor.
     * @property {module:model/CancelBookingRequest}
     */
    CancelBookingRequest,

    /**
     * The CheckAvailability200Response model constructor.
     * @property {module:model/CheckAvailability200Response}
     */
    CheckAvailability200Response,

    /**
     * The CheckAvailability200ResponseSlotsInner model constructor.
     * @property {module:model/CheckAvailability200ResponseSlotsInner}
     */
    CheckAvailability200ResponseSlotsInner,

    /**
     * The ConfirmOtp200Response model constructor.
     * @property {module:model/ConfirmOtp200Response}
     */
    ConfirmOtp200Response,

    /**
     * The ConfirmOtpRequest model constructor.
     * @property {module:model/ConfirmOtpRequest}
     */
    ConfirmOtpRequest,

    /**
     * The CreateBooking200Response model constructor.
     * @property {module:model/CreateBooking200Response}
     */
    CreateBooking200Response,

    /**
     * The CreateBooking200ResponsePricing model constructor.
     * @property {module:model/CreateBooking200ResponsePricing}
     */
    CreateBooking200ResponsePricing,

    /**
     * The CreateBookingRequest model constructor.
     * @property {module:model/CreateBookingRequest}
     */
    CreateBookingRequest,

    /**
     * The CreateBookingRequestScheduledBookingsInner model constructor.
     * @property {module:model/CreateBookingRequestScheduledBookingsInner}
     */
    CreateBookingRequestScheduledBookingsInner,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The GetInstructorRecommendations200Response model constructor.
     * @property {module:model/GetInstructorRecommendations200Response}
     */
    GetInstructorRecommendations200Response,

    /**
     * The GetInstructorRecommendations200ResponseRecommendationsInner model constructor.
     * @property {module:model/GetInstructorRecommendations200ResponseRecommendationsInner}
     */
    GetInstructorRecommendations200ResponseRecommendationsInner,

    /**
     * The GetPackages200Response model constructor.
     * @property {module:model/GetPackages200Response}
     */
    GetPackages200Response,

    /**
     * The GetPackages200ResponseTestPackage model constructor.
     * @property {module:model/GetPackages200ResponseTestPackage}
     */
    GetPackages200ResponseTestPackage,

    /**
     * The HandleIncomingCallRequest model constructor.
     * @property {module:model/HandleIncomingCallRequest}
     */
    HandleIncomingCallRequest,

    /**
     * The HandleVoicemailRequest model constructor.
     * @property {module:model/HandleVoicemailRequest}
     */
    HandleVoicemailRequest,

    /**
     * The HealthCheck200Response model constructor.
     * @property {module:model/HealthCheck200Response}
     */
    HealthCheck200Response,

    /**
     * The Instructor model constructor.
     * @property {module:model/Instructor}
     */
    Instructor,

    /**
     * The InstructorLocation model constructor.
     * @property {module:model/InstructorLocation}
     */
    InstructorLocation,

    /**
     * The LookupBookings200Response model constructor.
     * @property {module:model/LookupBookings200Response}
     */
    LookupBookings200Response,

    /**
     * The LookupBookings200ResponseBookingsInner model constructor.
     * @property {module:model/LookupBookings200ResponseBookingsInner}
     */
    LookupBookings200ResponseBookingsInner,

    /**
     * The LookupBookings200ResponseBookingsInnerInstructor model constructor.
     * @property {module:model/LookupBookings200ResponseBookingsInnerInstructor}
     */
    LookupBookings200ResponseBookingsInnerInstructor,

    /**
     * The LookupBookings400Response model constructor.
     * @property {module:model/LookupBookings400Response}
     */
    LookupBookings400Response,

    /**
     * The OtpResponse model constructor.
     * @property {module:model/OtpResponse}
     */
    OtpResponse,

    /**
     * The Package model constructor.
     * @property {module:model/Package}
     */
    Package,

    /**
     * The RescheduleBooking200Response model constructor.
     * @property {module:model/RescheduleBooking200Response}
     */
    RescheduleBooking200Response,

    /**
     * The RescheduleBookingRequest model constructor.
     * @property {module:model/RescheduleBookingRequest}
     */
    RescheduleBookingRequest,

    /**
     * The SearchInstructorsByLocation200Response model constructor.
     * @property {module:model/SearchInstructorsByLocation200Response}
     */
    SearchInstructorsByLocation200Response,

    /**
     * The SearchInstructorsByLocation200ResponseSearchLocation model constructor.
     * @property {module:model/SearchInstructorsByLocation200ResponseSearchLocation}
     */
    SearchInstructorsByLocation200ResponseSearchLocation,

    /**
     * The SendOtp200Response model constructor.
     * @property {module:model/SendOtp200Response}
     */
    SendOtp200Response,

    /**
     * The SendOtpRequest model constructor.
     * @property {module:model/SendOtpRequest}
     */
    SendOtpRequest,

    /**
     * The ValidateLocation200Response model constructor.
     * @property {module:model/ValidateLocation200Response}
     */
    ValidateLocation200Response,

    /**
     * The ValidateLocation200ResponseComponents model constructor.
     * @property {module:model/ValidateLocation200ResponseComponents}
     */
    ValidateLocation200ResponseComponents,

    /**
     * The ValidateLocationRequest model constructor.
     * @property {module:model/ValidateLocationRequest}
     */
    ValidateLocationRequest,

    /**
    * The AvailabilityApi service constructor.
    * @property {module:api/AvailabilityApi}
    */
    AvailabilityApi,

    /**
    * The BookingsApi service constructor.
    * @property {module:api/BookingsApi}
    */
    BookingsApi,

    /**
    * The InstructorsApi service constructor.
    * @property {module:api/InstructorsApi}
    */
    InstructorsApi,

    /**
    * The LocationsApi service constructor.
    * @property {module:api/LocationsApi}
    */
    LocationsApi,

    /**
    * The PackagesApi service constructor.
    * @property {module:api/PackagesApi}
    */
    PackagesApi,

    /**
    * The SystemApi service constructor.
    * @property {module:api/SystemApi}
    */
    SystemApi,

    /**
    * The VerificationsApi service constructor.
    * @property {module:api/VerificationsApi}
    */
    VerificationsApi,

    /**
    * The VoiceApi service constructor.
    * @property {module:api/VoiceApi}
    */
    VoiceApi
};
