export { default as WidgetCard } from './WidgetCard';
export * from './RevenueWidgets';
export * from './ProfitWidgets';
export * from './InventoryWidgets';
export * from './WarehouseWidgets';
export * from './SalesWidgets';
export * from './ProductionWidgets';
export * from './FinanceWidgets';
export * from './CustomerWidgets';
export * from './AIWidgets';
export * from './OperationsWidgets';
export * from './SupplierWidgets';
export * from './RiskWidgets';
export * from './ComplianceWidgets';
export * from './ForecastWidgets';