/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AvailabilityResponseSlotsInner model module.
 * @module model/AvailabilityResponseSlotsInner
 * @version 2.0.0
 */
class AvailabilityResponseSlotsInner {
    /**
     * Constructs a new <code>AvailabilityResponseSlotsInner</code>.
     * @alias module:model/AvailabilityResponseSlotsInner
     */
    constructor() { 
        
        AvailabilityResponseSlotsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AvailabilityResponseSlotsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AvailabilityResponseSlotsInner} obj Optional instance to populate.
     * @return {module:model/AvailabilityResponseSlotsInner} The populated <code>AvailabilityResponseSlotsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvailabilityResponseSlotsInner();

            if (data.hasOwnProperty('slotId')) {
                obj['slotId'] = ApiClient.convertToType(data['slotId'], 'String');
            }
            if (data.hasOwnProperty('instructorId')) {
                obj['instructorId'] = ApiClient.convertToType(data['instructorId'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'String');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'String');
            }
            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'Boolean');
            }
            if (data.hasOwnProperty('seats')) {
                obj['seats'] = ApiClient.convertToType(data['seats'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AvailabilityResponseSlotsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AvailabilityResponseSlotsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['slotId'] && !(typeof data['slotId'] === 'string' || data['slotId'] instanceof String)) {
            throw new Error("Expected the field `slotId` to be a primitive type in the JSON string but got " + data['slotId']);
        }
        // ensure the json data is a string
        if (data['instructorId'] && !(typeof data['instructorId'] === 'string' || data['instructorId'] instanceof String)) {
            throw new Error("Expected the field `instructorId` to be a primitive type in the JSON string but got " + data['instructorId']);
        }
        // ensure the json data is a string
        if (data['time'] && !(typeof data['time'] === 'string' || data['time'] instanceof String)) {
            throw new Error("Expected the field `time` to be a primitive type in the JSON string but got " + data['time']);
        }
        // ensure the json data is a string
        if (data['start'] && !(typeof data['start'] === 'string' || data['start'] instanceof String)) {
            throw new Error("Expected the field `start` to be a primitive type in the JSON string but got " + data['start']);
        }
        // ensure the json data is a string
        if (data['end'] && !(typeof data['end'] === 'string' || data['end'] instanceof String)) {
            throw new Error("Expected the field `end` to be a primitive type in the JSON string but got " + data['end']);
        }

        return true;
    }


}



/**
 * @member {String} slotId
 */
AvailabilityResponseSlotsInner.prototype['slotId'] = undefined;

/**
 * @member {String} instructorId
 */
AvailabilityResponseSlotsInner.prototype['instructorId'] = undefined;

/**
 * Local time (HH:MM)
 * @member {String} time
 */
AvailabilityResponseSlotsInner.prototype['time'] = undefined;

/**
 * ISO-8601 start datetime
 * @member {String} start
 */
AvailabilityResponseSlotsInner.prototype['start'] = undefined;

/**
 * ISO-8601 end datetime
 * @member {String} end
 */
AvailabilityResponseSlotsInner.prototype['end'] = undefined;

/**
 * @member {Boolean} available
 */
AvailabilityResponseSlotsInner.prototype['available'] = undefined;

/**
 * @member {Number} seats
 */
AvailabilityResponseSlotsInner.prototype['seats'] = undefined;






export default AvailabilityResponseSlotsInner;

