/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AvailabilityResponseSlotsInner from './AvailabilityResponseSlotsInner';

/**
 * The AvailabilityResponse model module.
 * @module model/AvailabilityResponse
 * @version 2.0.0
 */
class AvailabilityResponse {
    /**
     * Constructs a new <code>AvailabilityResponse</code>.
     * @alias module:model/AvailabilityResponse
     */
    constructor() { 
        
        AvailabilityResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AvailabilityResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AvailabilityResponse} obj Optional instance to populate.
     * @return {module:model/AvailabilityResponse} The populated <code>AvailabilityResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvailabilityResponse();

            if (data.hasOwnProperty('slots')) {
                obj['slots'] = ApiClient.convertToType(data['slots'], [AvailabilityResponseSlotsInner]);
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AvailabilityResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AvailabilityResponse</code>.
     */
    static validateJSON(data) {
        if (data['slots']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['slots'])) {
                throw new Error("Expected the field `slots` to be an array in the JSON data but got " + data['slots']);
            }
            // validate the optional field `slots` (array)
            for (const item of data['slots']) {
                AvailabilityResponseSlotsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['timezone'] && !(typeof data['timezone'] === 'string' || data['timezone'] instanceof String)) {
            throw new Error("Expected the field `timezone` to be a primitive type in the JSON string but got " + data['timezone']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/AvailabilityResponseSlotsInner>} slots
 */
AvailabilityResponse.prototype['slots'] = undefined;

/**
 * @member {Date} date
 */
AvailabilityResponse.prototype['date'] = undefined;

/**
 * @member {Number} duration
 */
AvailabilityResponse.prototype['duration'] = undefined;

/**
 * IANA timezone identifier (e.g., Australia/Perth)
 * @member {String} timezone
 */
AvailabilityResponse.prototype['timezone'] = undefined;

/**
 * ISO 4217 currency code
 * @member {String} currency
 */
AvailabilityResponse.prototype['currency'] = undefined;

/**
 * @member {String} notes
 */
AvailabilityResponse.prototype['notes'] = undefined;






export default AvailabilityResponse;

