/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BookingStatus.
* @enum {}
* @readonly
*/
export default class BookingStatus {
    
        /**
         * value: "pending"
         * @const
         */
        "pending" = "pending";

    
        /**
         * value: "confirmed"
         * @const
         */
        "confirmed" = "confirmed";

    
        /**
         * value: "cancelled"
         * @const
         */
        "cancelled" = "cancelled";

    
        /**
         * value: "rescheduled"
         * @const
         */
        "rescheduled" = "rescheduled";

    
        /**
         * value: "completed"
         * @const
         */
        "completed" = "completed";

    

    /**
    * Returns a <code>BookingStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BookingStatus} The enum <code>BookingStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

