/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BookingRequest model module.
 * @module model/BookingRequest
 * @version 2.0.0
 */
class BookingRequest {
    /**
     * Constructs a new <code>BookingRequest</code>.
     * @alias module:model/BookingRequest
     */
    constructor() { 
        
        BookingRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookingRequest} obj Optional instance to populate.
     * @return {module:model/BookingRequest} The populated <code>BookingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookingRequest();

            if (data.hasOwnProperty('instructorId')) {
                obj['instructorId'] = ApiClient.convertToType(data['instructorId'], 'String');
            }
            if (data.hasOwnProperty('instructorQuery')) {
                obj['instructorQuery'] = ApiClient.convertToType(data['instructorQuery'], 'String');
            }
            if (data.hasOwnProperty('packageType')) {
                obj['packageType'] = ApiClient.convertToType(data['packageType'], 'String');
            }
            if (data.hasOwnProperty('hours')) {
                obj['hours'] = ApiClient.convertToType(data['hours'], 'Number');
            }
            if (data.hasOwnProperty('bookingType')) {
                obj['bookingType'] = ApiClient.convertToType(data['bookingType'], 'String');
            }
            if (data.hasOwnProperty('registrationType')) {
                obj['registrationType'] = ApiClient.convertToType(data['registrationType'], 'String');
            }
            if (data.hasOwnProperty('accountHolderName')) {
                obj['accountHolderName'] = ApiClient.convertToType(data['accountHolderName'], 'String');
            }
            if (data.hasOwnProperty('accountHolderEmail')) {
                obj['accountHolderEmail'] = ApiClient.convertToType(data['accountHolderEmail'], 'String');
            }
            if (data.hasOwnProperty('accountHolderPhone')) {
                obj['accountHolderPhone'] = ApiClient.convertToType(data['accountHolderPhone'], 'String');
            }
            if (data.hasOwnProperty('scheduledBookings')) {
                obj['scheduledBookings'] = ApiClient.convertToType(data['scheduledBookings'], [Object]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BookingRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BookingRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['instructorId'] && !(typeof data['instructorId'] === 'string' || data['instructorId'] instanceof String)) {
            throw new Error("Expected the field `instructorId` to be a primitive type in the JSON string but got " + data['instructorId']);
        }
        // ensure the json data is a string
        if (data['instructorQuery'] && !(typeof data['instructorQuery'] === 'string' || data['instructorQuery'] instanceof String)) {
            throw new Error("Expected the field `instructorQuery` to be a primitive type in the JSON string but got " + data['instructorQuery']);
        }
        // ensure the json data is a string
        if (data['packageType'] && !(typeof data['packageType'] === 'string' || data['packageType'] instanceof String)) {
            throw new Error("Expected the field `packageType` to be a primitive type in the JSON string but got " + data['packageType']);
        }
        // ensure the json data is a string
        if (data['bookingType'] && !(typeof data['bookingType'] === 'string' || data['bookingType'] instanceof String)) {
            throw new Error("Expected the field `bookingType` to be a primitive type in the JSON string but got " + data['bookingType']);
        }
        // ensure the json data is a string
        if (data['registrationType'] && !(typeof data['registrationType'] === 'string' || data['registrationType'] instanceof String)) {
            throw new Error("Expected the field `registrationType` to be a primitive type in the JSON string but got " + data['registrationType']);
        }
        // ensure the json data is a string
        if (data['accountHolderName'] && !(typeof data['accountHolderName'] === 'string' || data['accountHolderName'] instanceof String)) {
            throw new Error("Expected the field `accountHolderName` to be a primitive type in the JSON string but got " + data['accountHolderName']);
        }
        // ensure the json data is a string
        if (data['accountHolderEmail'] && !(typeof data['accountHolderEmail'] === 'string' || data['accountHolderEmail'] instanceof String)) {
            throw new Error("Expected the field `accountHolderEmail` to be a primitive type in the JSON string but got " + data['accountHolderEmail']);
        }
        // ensure the json data is a string
        if (data['accountHolderPhone'] && !(typeof data['accountHolderPhone'] === 'string' || data['accountHolderPhone'] instanceof String)) {
            throw new Error("Expected the field `accountHolderPhone` to be a primitive type in the JSON string but got " + data['accountHolderPhone']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['scheduledBookings'])) {
            throw new Error("Expected the field `scheduledBookings` to be an array in the JSON data but got " + data['scheduledBookings']);
        }

        return true;
    }


}



/**
 * @member {String} instructorId
 */
BookingRequest.prototype['instructorId'] = undefined;

/**
 * @member {String} instructorQuery
 */
BookingRequest.prototype['instructorQuery'] = undefined;

/**
 * @member {String} packageType
 */
BookingRequest.prototype['packageType'] = undefined;

/**
 * @member {Number} hours
 */
BookingRequest.prototype['hours'] = undefined;

/**
 * @member {String} bookingType
 */
BookingRequest.prototype['bookingType'] = undefined;

/**
 * @member {String} registrationType
 */
BookingRequest.prototype['registrationType'] = undefined;

/**
 * @member {String} accountHolderName
 */
BookingRequest.prototype['accountHolderName'] = undefined;

/**
 * @member {String} accountHolderEmail
 */
BookingRequest.prototype['accountHolderEmail'] = undefined;

/**
 * @member {String} accountHolderPhone
 */
BookingRequest.prototype['accountHolderPhone'] = undefined;

/**
 * @member {Array.<Object>} scheduledBookings
 */
BookingRequest.prototype['scheduledBookings'] = undefined;






export default BookingRequest;

