/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CheckAvailability200ResponseSlotsInner from './CheckAvailability200ResponseSlotsInner';

/**
 * The CheckAvailability200Response model module.
 * @module model/CheckAvailability200Response
 * @version 2.0.0
 */
class CheckAvailability200Response {
    /**
     * Constructs a new <code>CheckAvailability200Response</code>.
     * @alias module:model/CheckAvailability200Response
     */
    constructor() { 
        
        CheckAvailability200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CheckAvailability200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckAvailability200Response} obj Optional instance to populate.
     * @return {module:model/CheckAvailability200Response} The populated <code>CheckAvailability200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckAvailability200Response();

            if (data.hasOwnProperty('slots')) {
                obj['slots'] = ApiClient.convertToType(data['slots'], [CheckAvailability200ResponseSlotsInner]);
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CheckAvailability200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CheckAvailability200Response</code>.
     */
    static validateJSON(data) {
        if (data['slots']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['slots'])) {
                throw new Error("Expected the field `slots` to be an array in the JSON data but got " + data['slots']);
            }
            // validate the optional field `slots` (array)
            for (const item of data['slots']) {
                CheckAvailability200ResponseSlotsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/CheckAvailability200ResponseSlotsInner>} slots
 */
CheckAvailability200Response.prototype['slots'] = undefined;

/**
 * @member {Date} date
 */
CheckAvailability200Response.prototype['date'] = undefined;

/**
 * @member {Number} duration
 */
CheckAvailability200Response.prototype['duration'] = undefined;






export default CheckAvailability200Response;

