/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfirmOtpRequest model module.
 * @module model/ConfirmOtpRequest
 * @version 2.0.0
 */
class ConfirmOtpRequest {
    /**
     * Constructs a new <code>ConfirmOtpRequest</code>.
     * @alias module:model/ConfirmOtpRequest
     * @param verificationId {String} 
     * @param code {String} Numeric or alphanumeric OTP code
     */
    constructor(verificationId, code) { 
        
        ConfirmOtpRequest.initialize(this, verificationId, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, verificationId, code) { 
        obj['verificationId'] = verificationId;
        obj['code'] = code;
    }

    /**
     * Constructs a <code>ConfirmOtpRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfirmOtpRequest} obj Optional instance to populate.
     * @return {module:model/ConfirmOtpRequest} The populated <code>ConfirmOtpRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfirmOtpRequest();

            if (data.hasOwnProperty('verificationId')) {
                obj['verificationId'] = ApiClient.convertToType(data['verificationId'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfirmOtpRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfirmOtpRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ConfirmOtpRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['verificationId'] && !(typeof data['verificationId'] === 'string' || data['verificationId'] instanceof String)) {
            throw new Error("Expected the field `verificationId` to be a primitive type in the JSON string but got " + data['verificationId']);
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }

        return true;
    }


}

ConfirmOtpRequest.RequiredProperties = ["verificationId", "code"];

/**
 * @member {String} verificationId
 */
ConfirmOtpRequest.prototype['verificationId'] = undefined;

/**
 * Numeric or alphanumeric OTP code
 * @member {String} code
 */
ConfirmOtpRequest.prototype['code'] = undefined;






export default ConfirmOtpRequest;

