/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateBooking200ResponsePricing model module.
 * @module model/CreateBooking200ResponsePricing
 * @version 2.0.0
 */
class CreateBooking200ResponsePricing {
    /**
     * Constructs a new <code>CreateBooking200ResponsePricing</code>.
     * Pricing breakdown (calculated by backend)
     * @alias module:model/CreateBooking200ResponsePricing
     */
    constructor() { 
        
        CreateBooking200ResponsePricing.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateBooking200ResponsePricing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateBooking200ResponsePricing} obj Optional instance to populate.
     * @return {module:model/CreateBooking200ResponsePricing} The populated <code>CreateBooking200ResponsePricing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBooking200ResponsePricing();

            if (data.hasOwnProperty('subtotal')) {
                obj['subtotal'] = ApiClient.convertToType(data['subtotal'], 'Number');
            }
            if (data.hasOwnProperty('discount')) {
                obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
            }
            if (data.hasOwnProperty('platformFee')) {
                obj['platformFee'] = ApiClient.convertToType(data['platformFee'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateBooking200ResponsePricing</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateBooking200ResponsePricing</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} subtotal
 */
CreateBooking200ResponsePricing.prototype['subtotal'] = undefined;

/**
 * @member {Number} discount
 */
CreateBooking200ResponsePricing.prototype['discount'] = undefined;

/**
 * @member {Number} platformFee
 */
CreateBooking200ResponsePricing.prototype['platformFee'] = undefined;

/**
 * @member {Number} total
 */
CreateBooking200ResponsePricing.prototype['total'] = undefined;






export default CreateBooking200ResponsePricing;

