/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateBookingRequestScheduledBookingsInner model module.
 * @module model/CreateBookingRequestScheduledBookingsInner
 * @version 2.0.0
 */
class CreateBookingRequestScheduledBookingsInner {
    /**
     * Constructs a new <code>CreateBookingRequestScheduledBookingsInner</code>.
     * @alias module:model/CreateBookingRequestScheduledBookingsInner
     * @param date {String} 
     * @param time {String} 
     * @param duration {Number} 
     * @param pickupLocation {String} 
     */
    constructor(date, time, duration, pickupLocation) { 
        
        CreateBookingRequestScheduledBookingsInner.initialize(this, date, time, duration, pickupLocation);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, time, duration, pickupLocation) { 
        obj['date'] = date;
        obj['time'] = time;
        obj['duration'] = duration;
        obj['pickupLocation'] = pickupLocation;
    }

    /**
     * Constructs a <code>CreateBookingRequestScheduledBookingsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateBookingRequestScheduledBookingsInner} obj Optional instance to populate.
     * @return {module:model/CreateBookingRequestScheduledBookingsInner} The populated <code>CreateBookingRequestScheduledBookingsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBookingRequestScheduledBookingsInner();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('pickupLocation')) {
                obj['pickupLocation'] = ApiClient.convertToType(data['pickupLocation'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateBookingRequestScheduledBookingsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateBookingRequestScheduledBookingsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateBookingRequestScheduledBookingsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['time'] && !(typeof data['time'] === 'string' || data['time'] instanceof String)) {
            throw new Error("Expected the field `time` to be a primitive type in the JSON string but got " + data['time']);
        }
        // ensure the json data is a string
        if (data['pickupLocation'] && !(typeof data['pickupLocation'] === 'string' || data['pickupLocation'] instanceof String)) {
            throw new Error("Expected the field `pickupLocation` to be a primitive type in the JSON string but got " + data['pickupLocation']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }

        return true;
    }


}

CreateBookingRequestScheduledBookingsInner.RequiredProperties = ["date", "time", "duration", "pickupLocation"];

/**
 * @member {String} date
 */
CreateBookingRequestScheduledBookingsInner.prototype['date'] = undefined;

/**
 * @member {String} time
 */
CreateBookingRequestScheduledBookingsInner.prototype['time'] = undefined;

/**
 * @member {Number} duration
 */
CreateBookingRequestScheduledBookingsInner.prototype['duration'] = undefined;

/**
 * @member {String} pickupLocation
 */
CreateBookingRequestScheduledBookingsInner.prototype['pickupLocation'] = undefined;

/**
 * @member {String} notes
 */
CreateBookingRequestScheduledBookingsInner.prototype['notes'] = undefined;






export default CreateBookingRequestScheduledBookingsInner;

