/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateBookingRequestScheduledBookingsInner from './CreateBookingRequestScheduledBookingsInner';

/**
 * The CreateBookingRequest model module.
 * @module model/CreateBookingRequest
 * @version 2.0.0
 */
class CreateBookingRequest {
    /**
     * Constructs a new <code>CreateBookingRequest</code>.
     * @alias module:model/CreateBookingRequest
     * @param packageType {module:model/CreateBookingRequest.PackageTypeEnum} 
     * @param bookingType {module:model/CreateBookingRequest.BookingTypeEnum} Schedule now or buy credits for later
     * @param registrationType {module:model/CreateBookingRequest.RegistrationTypeEnum} 
     * @param accountHolderName {String} 
     * @param accountHolderEmail {String} 
     * @param accountHolderPhone {String} Phone number - password will be auto-generated and sent via SMS/email
     */
    constructor(packageType, bookingType, registrationType, accountHolderName, accountHolderEmail, accountHolderPhone) { 
        
        CreateBookingRequest.initialize(this, packageType, bookingType, registrationType, accountHolderName, accountHolderEmail, accountHolderPhone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, packageType, bookingType, registrationType, accountHolderName, accountHolderEmail, accountHolderPhone) { 
        obj['packageType'] = packageType;
        obj['includeTestPackage'] = false;
        obj['bookingType'] = bookingType;
        obj['registrationType'] = registrationType;
        obj['accountHolderName'] = accountHolderName;
        obj['accountHolderEmail'] = accountHolderEmail;
        obj['accountHolderPhone'] = accountHolderPhone;
    }

    /**
     * Constructs a <code>CreateBookingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateBookingRequest} obj Optional instance to populate.
     * @return {module:model/CreateBookingRequest} The populated <code>CreateBookingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBookingRequest();

            if (data.hasOwnProperty('instructorId')) {
                obj['instructorId'] = ApiClient.convertToType(data['instructorId'], 'String');
            }
            if (data.hasOwnProperty('instructorQuery')) {
                obj['instructorQuery'] = ApiClient.convertToType(data['instructorQuery'], 'String');
            }
            if (data.hasOwnProperty('packageType')) {
                obj['packageType'] = ApiClient.convertToType(data['packageType'], 'String');
            }
            if (data.hasOwnProperty('hours')) {
                obj['hours'] = ApiClient.convertToType(data['hours'], 'Number');
            }
            if (data.hasOwnProperty('includeTestPackage')) {
                obj['includeTestPackage'] = ApiClient.convertToType(data['includeTestPackage'], 'Boolean');
            }
            if (data.hasOwnProperty('bookingType')) {
                obj['bookingType'] = ApiClient.convertToType(data['bookingType'], 'String');
            }
            if (data.hasOwnProperty('registrationType')) {
                obj['registrationType'] = ApiClient.convertToType(data['registrationType'], 'String');
            }
            if (data.hasOwnProperty('accountHolderName')) {
                obj['accountHolderName'] = ApiClient.convertToType(data['accountHolderName'], 'String');
            }
            if (data.hasOwnProperty('accountHolderEmail')) {
                obj['accountHolderEmail'] = ApiClient.convertToType(data['accountHolderEmail'], 'String');
            }
            if (data.hasOwnProperty('accountHolderPhone')) {
                obj['accountHolderPhone'] = ApiClient.convertToType(data['accountHolderPhone'], 'String');
            }
            if (data.hasOwnProperty('learnerName')) {
                obj['learnerName'] = ApiClient.convertToType(data['learnerName'], 'String');
            }
            if (data.hasOwnProperty('learnerPhone')) {
                obj['learnerPhone'] = ApiClient.convertToType(data['learnerPhone'], 'String');
            }
            if (data.hasOwnProperty('learnerRelationship')) {
                obj['learnerRelationship'] = ApiClient.convertToType(data['learnerRelationship'], 'String');
            }
            if (data.hasOwnProperty('scheduledBookings')) {
                obj['scheduledBookings'] = ApiClient.convertToType(data['scheduledBookings'], [CreateBookingRequestScheduledBookingsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateBookingRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateBookingRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateBookingRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['instructorId'] && !(typeof data['instructorId'] === 'string' || data['instructorId'] instanceof String)) {
            throw new Error("Expected the field `instructorId` to be a primitive type in the JSON string but got " + data['instructorId']);
        }
        // ensure the json data is a string
        if (data['instructorQuery'] && !(typeof data['instructorQuery'] === 'string' || data['instructorQuery'] instanceof String)) {
            throw new Error("Expected the field `instructorQuery` to be a primitive type in the JSON string but got " + data['instructorQuery']);
        }
        // ensure the json data is a string
        if (data['packageType'] && !(typeof data['packageType'] === 'string' || data['packageType'] instanceof String)) {
            throw new Error("Expected the field `packageType` to be a primitive type in the JSON string but got " + data['packageType']);
        }
        // ensure the json data is a string
        if (data['bookingType'] && !(typeof data['bookingType'] === 'string' || data['bookingType'] instanceof String)) {
            throw new Error("Expected the field `bookingType` to be a primitive type in the JSON string but got " + data['bookingType']);
        }
        // ensure the json data is a string
        if (data['registrationType'] && !(typeof data['registrationType'] === 'string' || data['registrationType'] instanceof String)) {
            throw new Error("Expected the field `registrationType` to be a primitive type in the JSON string but got " + data['registrationType']);
        }
        // ensure the json data is a string
        if (data['accountHolderName'] && !(typeof data['accountHolderName'] === 'string' || data['accountHolderName'] instanceof String)) {
            throw new Error("Expected the field `accountHolderName` to be a primitive type in the JSON string but got " + data['accountHolderName']);
        }
        // ensure the json data is a string
        if (data['accountHolderEmail'] && !(typeof data['accountHolderEmail'] === 'string' || data['accountHolderEmail'] instanceof String)) {
            throw new Error("Expected the field `accountHolderEmail` to be a primitive type in the JSON string but got " + data['accountHolderEmail']);
        }
        // ensure the json data is a string
        if (data['accountHolderPhone'] && !(typeof data['accountHolderPhone'] === 'string' || data['accountHolderPhone'] instanceof String)) {
            throw new Error("Expected the field `accountHolderPhone` to be a primitive type in the JSON string but got " + data['accountHolderPhone']);
        }
        // ensure the json data is a string
        if (data['learnerName'] && !(typeof data['learnerName'] === 'string' || data['learnerName'] instanceof String)) {
            throw new Error("Expected the field `learnerName` to be a primitive type in the JSON string but got " + data['learnerName']);
        }
        // ensure the json data is a string
        if (data['learnerPhone'] && !(typeof data['learnerPhone'] === 'string' || data['learnerPhone'] instanceof String)) {
            throw new Error("Expected the field `learnerPhone` to be a primitive type in the JSON string but got " + data['learnerPhone']);
        }
        // ensure the json data is a string
        if (data['learnerRelationship'] && !(typeof data['learnerRelationship'] === 'string' || data['learnerRelationship'] instanceof String)) {
            throw new Error("Expected the field `learnerRelationship` to be a primitive type in the JSON string but got " + data['learnerRelationship']);
        }
        if (data['scheduledBookings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['scheduledBookings'])) {
                throw new Error("Expected the field `scheduledBookings` to be an array in the JSON data but got " + data['scheduledBookings']);
            }
            // validate the optional field `scheduledBookings` (array)
            for (const item of data['scheduledBookings']) {
                CreateBookingRequestScheduledBookingsInner.validateJSON(item);
            };
        }

        return true;
    }


}

CreateBookingRequest.RequiredProperties = ["packageType", "bookingType", "registrationType", "accountHolderName", "accountHolderEmail", "accountHolderPhone"];

/**
 * Instructor ID resolved from API responses. Use when you have the ID from GET /instructors/recommendations or GET /instructors/search. Either instructorId or instructorQuery must be provided. 
 * @member {String} instructorId
 */
CreateBookingRequest.prototype['instructorId'] = undefined;

/**
 * Optional: instructor name or phone number. Use when you only have a name (e.g. \"Debesay\") or phone number. Backend will resolve to an instructorId automatically. Either instructorId or instructorQuery must be provided. Examples: \"Debesay\", \"Debesay Birhane\", \"0400123456\" 
 * @member {String} instructorQuery
 */
CreateBookingRequest.prototype['instructorQuery'] = undefined;

/**
 * @member {module:model/CreateBookingRequest.PackageTypeEnum} packageType
 */
CreateBookingRequest.prototype['packageType'] = undefined;

/**
 * Required only for CUSTOM package
 * @member {Number} hours
 */
CreateBookingRequest.prototype['hours'] = undefined;

/**
 * @member {Boolean} includeTestPackage
 * @default false
 */
CreateBookingRequest.prototype['includeTestPackage'] = false;

/**
 * Schedule now or buy credits for later
 * @member {module:model/CreateBookingRequest.BookingTypeEnum} bookingType
 */
CreateBookingRequest.prototype['bookingType'] = undefined;

/**
 * @member {module:model/CreateBookingRequest.RegistrationTypeEnum} registrationType
 */
CreateBookingRequest.prototype['registrationType'] = undefined;

/**
 * @member {String} accountHolderName
 */
CreateBookingRequest.prototype['accountHolderName'] = undefined;

/**
 * @member {String} accountHolderEmail
 */
CreateBookingRequest.prototype['accountHolderEmail'] = undefined;

/**
 * Phone number - password will be auto-generated and sent via SMS/email
 * @member {String} accountHolderPhone
 */
CreateBookingRequest.prototype['accountHolderPhone'] = undefined;

/**
 * Required if registrationType is someone-else
 * @member {String} learnerName
 */
CreateBookingRequest.prototype['learnerName'] = undefined;

/**
 * @member {String} learnerPhone
 */
CreateBookingRequest.prototype['learnerPhone'] = undefined;

/**
 * @member {module:model/CreateBookingRequest.LearnerRelationshipEnum} learnerRelationship
 */
CreateBookingRequest.prototype['learnerRelationship'] = undefined;

/**
 * Required if bookingType is now
 * @member {Array.<module:model/CreateBookingRequestScheduledBookingsInner>} scheduledBookings
 */
CreateBookingRequest.prototype['scheduledBookings'] = undefined;





/**
 * Allowed values for the <code>packageType</code> property.
 * @enum {String}
 * @readonly
 */
CreateBookingRequest['PackageTypeEnum'] = {

    /**
     * value: "PACKAGE_6"
     * @const
     */
    "PACKAGE_6": "PACKAGE_6",

    /**
     * value: "PACKAGE_10"
     * @const
     */
    "PACKAGE_10": "PACKAGE_10",

    /**
     * value: "PACKAGE_15"
     * @const
     */
    "PACKAGE_15": "PACKAGE_15",

    /**
     * value: "CUSTOM"
     * @const
     */
    "CUSTOM": "CUSTOM"
};


/**
 * Allowed values for the <code>bookingType</code> property.
 * @enum {String}
 * @readonly
 */
CreateBookingRequest['BookingTypeEnum'] = {

    /**
     * value: "now"
     * @const
     */
    "now": "now",

    /**
     * value: "later"
     * @const
     */
    "later": "later"
};


/**
 * Allowed values for the <code>registrationType</code> property.
 * @enum {String}
 * @readonly
 */
CreateBookingRequest['RegistrationTypeEnum'] = {

    /**
     * value: "myself"
     * @const
     */
    "myself": "myself",

    /**
     * value: "someone-else"
     * @const
     */
    "someone-else": "someone-else"
};


/**
 * Allowed values for the <code>learnerRelationship</code> property.
 * @enum {String}
 * @readonly
 */
CreateBookingRequest['LearnerRelationshipEnum'] = {

    /**
     * value: "child"
     * @const
     */
    "child": "child",

    /**
     * value: "partner"
     * @const
     */
    "partner": "partner",

    /**
     * value: "grandchild"
     * @const
     */
    "grandchild": "grandchild",

    /**
     * value: "parent"
     * @const
     */
    "parent": "parent",

    /**
     * value: "friend"
     * @const
     */
    "friend": "friend",

    /**
     * value: "other"
     * @const
     */
    "other": "other"
};



export default CreateBookingRequest;

