/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetInstructorRecommendations200ResponseRecommendationsInner from './GetInstructorRecommendations200ResponseRecommendationsInner';

/**
 * The GetInstructorRecommendations200Response model module.
 * @module model/GetInstructorRecommendations200Response
 * @version 2.0.0
 */
class GetInstructorRecommendations200Response {
    /**
     * Constructs a new <code>GetInstructorRecommendations200Response</code>.
     * @alias module:model/GetInstructorRecommendations200Response
     */
    constructor() { 
        
        GetInstructorRecommendations200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetInstructorRecommendations200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetInstructorRecommendations200Response} obj Optional instance to populate.
     * @return {module:model/GetInstructorRecommendations200Response} The populated <code>GetInstructorRecommendations200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetInstructorRecommendations200Response();

            if (data.hasOwnProperty('recommendations')) {
                obj['recommendations'] = ApiClient.convertToType(data['recommendations'], [GetInstructorRecommendations200ResponseRecommendationsInner]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetInstructorRecommendations200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetInstructorRecommendations200Response</code>.
     */
    static validateJSON(data) {
        if (data['recommendations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['recommendations'])) {
                throw new Error("Expected the field `recommendations` to be an array in the JSON data but got " + data['recommendations']);
            }
            // validate the optional field `recommendations` (array)
            for (const item of data['recommendations']) {
                GetInstructorRecommendations200ResponseRecommendationsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/GetInstructorRecommendations200ResponseRecommendationsInner>} recommendations
 */
GetInstructorRecommendations200Response.prototype['recommendations'] = undefined;

/**
 * @member {Number} count
 */
GetInstructorRecommendations200Response.prototype['count'] = undefined;

/**
 * @member {String} message
 */
GetInstructorRecommendations200Response.prototype['message'] = undefined;






export default GetInstructorRecommendations200Response;

