/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetInstructorRecommendations200ResponseRecommendationsInner model module.
 * @module model/GetInstructorRecommendations200ResponseRecommendationsInner
 * @version 2.0.0
 */
class GetInstructorRecommendations200ResponseRecommendationsInner {
    /**
     * Constructs a new <code>GetInstructorRecommendations200ResponseRecommendationsInner</code>.
     * @alias module:model/GetInstructorRecommendations200ResponseRecommendationsInner
     */
    constructor() { 
        
        GetInstructorRecommendations200ResponseRecommendationsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetInstructorRecommendations200ResponseRecommendationsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetInstructorRecommendations200ResponseRecommendationsInner} obj Optional instance to populate.
     * @return {module:model/GetInstructorRecommendations200ResponseRecommendationsInner} The populated <code>GetInstructorRecommendations200ResponseRecommendationsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetInstructorRecommendations200ResponseRecommendationsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('hourlyRate')) {
                obj['hourlyRate'] = ApiClient.convertToType(data['hourlyRate'], 'Number');
            }
            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
            }
            if (data.hasOwnProperty('reviews')) {
                obj['reviews'] = ApiClient.convertToType(data['reviews'], 'Number');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetInstructorRecommendations200ResponseRecommendationsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetInstructorRecommendations200ResponseRecommendationsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['reason'] && !(typeof data['reason'] === 'string' || data['reason'] instanceof String)) {
            throw new Error("Expected the field `reason` to be a primitive type in the JSON string but got " + data['reason']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
GetInstructorRecommendations200ResponseRecommendationsInner.prototype['id'] = undefined;

/**
 * @member {String} name
 */
GetInstructorRecommendations200ResponseRecommendationsInner.prototype['name'] = undefined;

/**
 * @member {Number} hourlyRate
 */
GetInstructorRecommendations200ResponseRecommendationsInner.prototype['hourlyRate'] = undefined;

/**
 * @member {Number} distance
 */
GetInstructorRecommendations200ResponseRecommendationsInner.prototype['distance'] = undefined;

/**
 * @member {Number} reviews
 */
GetInstructorRecommendations200ResponseRecommendationsInner.prototype['reviews'] = undefined;

/**
 * @member {String} reason
 */
GetInstructorRecommendations200ResponseRecommendationsInner.prototype['reason'] = undefined;

/**
 * @member {Number} score
 */
GetInstructorRecommendations200ResponseRecommendationsInner.prototype['score'] = undefined;






export default GetInstructorRecommendations200ResponseRecommendationsInner;

