/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetPackages200ResponseTestPackage model module.
 * @module model/GetPackages200ResponseTestPackage
 * @version 2.0.0
 */
class GetPackages200ResponseTestPackage {
    /**
     * Constructs a new <code>GetPackages200ResponseTestPackage</code>.
     * @alias module:model/GetPackages200ResponseTestPackage
     */
    constructor() { 
        
        GetPackages200ResponseTestPackage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetPackages200ResponseTestPackage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPackages200ResponseTestPackage} obj Optional instance to populate.
     * @return {module:model/GetPackages200ResponseTestPackage} The populated <code>GetPackages200ResponseTestPackage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPackages200ResponseTestPackage();

            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'Boolean');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('includes')) {
                obj['includes'] = ApiClient.convertToType(data['includes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetPackages200ResponseTestPackage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetPackages200ResponseTestPackage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['includes'] && !(typeof data['includes'] === 'string' || data['includes'] instanceof String)) {
            throw new Error("Expected the field `includes` to be a primitive type in the JSON string but got " + data['includes']);
        }

        return true;
    }


}



/**
 * @member {Boolean} available
 */
GetPackages200ResponseTestPackage.prototype['available'] = undefined;

/**
 * @member {Number} price
 */
GetPackages200ResponseTestPackage.prototype['price'] = undefined;

/**
 * @member {String} includes
 */
GetPackages200ResponseTestPackage.prototype['includes'] = undefined;






export default GetPackages200ResponseTestPackage;

