/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetPackages200ResponseTestPackage from './GetPackages200ResponseTestPackage';
import Package from './Package';

/**
 * The GetPackages200Response model module.
 * @module model/GetPackages200Response
 * @version 2.0.0
 */
class GetPackages200Response {
    /**
     * Constructs a new <code>GetPackages200Response</code>.
     * @alias module:model/GetPackages200Response
     */
    constructor() { 
        
        GetPackages200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetPackages200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPackages200Response} obj Optional instance to populate.
     * @return {module:model/GetPackages200Response} The populated <code>GetPackages200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPackages200Response();

            if (data.hasOwnProperty('packages')) {
                obj['packages'] = ApiClient.convertToType(data['packages'], [Package]);
            }
            if (data.hasOwnProperty('testPackage')) {
                obj['testPackage'] = GetPackages200ResponseTestPackage.constructFromObject(data['testPackage']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetPackages200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetPackages200Response</code>.
     */
    static validateJSON(data) {
        if (data['packages']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['packages'])) {
                throw new Error("Expected the field `packages` to be an array in the JSON data but got " + data['packages']);
            }
            // validate the optional field `packages` (array)
            for (const item of data['packages']) {
                Package.validateJSON(item);
            };
        }
        // validate the optional field `testPackage`
        if (data['testPackage']) { // data not null
          GetPackages200ResponseTestPackage.validateJSON(data['testPackage']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Package>} packages
 */
GetPackages200Response.prototype['packages'] = undefined;

/**
 * @member {module:model/GetPackages200ResponseTestPackage} testPackage
 */
GetPackages200Response.prototype['testPackage'] = undefined;






export default GetPackages200Response;

