/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HandleIncomingCallRequest model module.
 * @module model/HandleIncomingCallRequest
 * @version 2.0.0
 */
class HandleIncomingCallRequest {
    /**
     * Constructs a new <code>HandleIncomingCallRequest</code>.
     * @alias module:model/HandleIncomingCallRequest
     */
    constructor() { 
        
        HandleIncomingCallRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HandleIncomingCallRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HandleIncomingCallRequest} obj Optional instance to populate.
     * @return {module:model/HandleIncomingCallRequest} The populated <code>HandleIncomingCallRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HandleIncomingCallRequest();

            if (data.hasOwnProperty('From')) {
                obj['From'] = ApiClient.convertToType(data['From'], 'String');
            }
            if (data.hasOwnProperty('To')) {
                obj['To'] = ApiClient.convertToType(data['To'], 'String');
            }
            if (data.hasOwnProperty('CallSid')) {
                obj['CallSid'] = ApiClient.convertToType(data['CallSid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HandleIncomingCallRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HandleIncomingCallRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['From'] && !(typeof data['From'] === 'string' || data['From'] instanceof String)) {
            throw new Error("Expected the field `From` to be a primitive type in the JSON string but got " + data['From']);
        }
        // ensure the json data is a string
        if (data['To'] && !(typeof data['To'] === 'string' || data['To'] instanceof String)) {
            throw new Error("Expected the field `To` to be a primitive type in the JSON string but got " + data['To']);
        }
        // ensure the json data is a string
        if (data['CallSid'] && !(typeof data['CallSid'] === 'string' || data['CallSid'] instanceof String)) {
            throw new Error("Expected the field `CallSid` to be a primitive type in the JSON string but got " + data['CallSid']);
        }

        return true;
    }


}



/**
 * @member {String} From
 */
HandleIncomingCallRequest.prototype['From'] = undefined;

/**
 * @member {String} To
 */
HandleIncomingCallRequest.prototype['To'] = undefined;

/**
 * @member {String} CallSid
 */
HandleIncomingCallRequest.prototype['CallSid'] = undefined;






export default HandleIncomingCallRequest;

