/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstructorLocation from './InstructorLocation';

/**
 * The Instructor model module.
 * @module model/Instructor
 * @version 2.0.0
 */
class Instructor {
    /**
     * Constructs a new <code>Instructor</code>.
     * @alias module:model/Instructor
     */
    constructor() { 
        
        Instructor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Instructor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Instructor} obj Optional instance to populate.
     * @return {module:model/Instructor} The populated <code>Instructor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Instructor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('hourlyRate')) {
                obj['hourlyRate'] = ApiClient.convertToType(data['hourlyRate'], 'Number');
            }
            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('reviews')) {
                obj['reviews'] = ApiClient.convertToType(data['reviews'], 'Number');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('vehicleTypes')) {
                obj['vehicleTypes'] = ApiClient.convertToType(data['vehicleTypes'], ['String']);
            }
            if (data.hasOwnProperty('languages')) {
                obj['languages'] = ApiClient.convertToType(data['languages'], ['String']);
            }
            if (data.hasOwnProperty('profileImage')) {
                obj['profileImage'] = ApiClient.convertToType(data['profileImage'], 'String');
            }
            if (data.hasOwnProperty('totalBookings')) {
                obj['totalBookings'] = ApiClient.convertToType(data['totalBookings'], 'Number');
            }
            if (data.hasOwnProperty('carMake')) {
                obj['carMake'] = ApiClient.convertToType(data['carMake'], 'String');
            }
            if (data.hasOwnProperty('carModel')) {
                obj['carModel'] = ApiClient.convertToType(data['carModel'], 'String');
            }
            if (data.hasOwnProperty('carYear')) {
                obj['carYear'] = ApiClient.convertToType(data['carYear'], 'Number');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = InstructorLocation.constructFromObject(data['location']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Instructor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Instructor</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['bio'] && !(typeof data['bio'] === 'string' || data['bio'] instanceof String)) {
            throw new Error("Expected the field `bio` to be a primitive type in the JSON string but got " + data['bio']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['vehicleTypes'])) {
            throw new Error("Expected the field `vehicleTypes` to be an array in the JSON data but got " + data['vehicleTypes']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['languages'])) {
            throw new Error("Expected the field `languages` to be an array in the JSON data but got " + data['languages']);
        }
        // ensure the json data is a string
        if (data['profileImage'] && !(typeof data['profileImage'] === 'string' || data['profileImage'] instanceof String)) {
            throw new Error("Expected the field `profileImage` to be a primitive type in the JSON string but got " + data['profileImage']);
        }
        // ensure the json data is a string
        if (data['carMake'] && !(typeof data['carMake'] === 'string' || data['carMake'] instanceof String)) {
            throw new Error("Expected the field `carMake` to be a primitive type in the JSON string but got " + data['carMake']);
        }
        // ensure the json data is a string
        if (data['carModel'] && !(typeof data['carModel'] === 'string' || data['carModel'] instanceof String)) {
            throw new Error("Expected the field `carModel` to be a primitive type in the JSON string but got " + data['carModel']);
        }
        // validate the optional field `location`
        if (data['location']) { // data not null
          InstructorLocation.validateJSON(data['location']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
Instructor.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Instructor.prototype['name'] = undefined;

/**
 * @member {Number} hourlyRate
 */
Instructor.prototype['hourlyRate'] = undefined;

/**
 * @member {Number} distance
 */
Instructor.prototype['distance'] = undefined;

/**
 * @member {Number} rating
 */
Instructor.prototype['rating'] = undefined;

/**
 * @member {Number} reviews
 */
Instructor.prototype['reviews'] = undefined;

/**
 * @member {String} bio
 */
Instructor.prototype['bio'] = undefined;

/**
 * @member {Array.<String>} vehicleTypes
 */
Instructor.prototype['vehicleTypes'] = undefined;

/**
 * @member {Array.<String>} languages
 */
Instructor.prototype['languages'] = undefined;

/**
 * @member {String} profileImage
 */
Instructor.prototype['profileImage'] = undefined;

/**
 * @member {Number} totalBookings
 */
Instructor.prototype['totalBookings'] = undefined;

/**
 * @member {String} carMake
 */
Instructor.prototype['carMake'] = undefined;

/**
 * @member {String} carModel
 */
Instructor.prototype['carModel'] = undefined;

/**
 * @member {Number} carYear
 */
Instructor.prototype['carYear'] = undefined;

/**
 * @member {module:model/InstructorLocation} location
 */
Instructor.prototype['location'] = undefined;






export default Instructor;

