/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BookingStatus from './BookingStatus';
import LookupBookings200ResponseBookingsInnerInstructor from './LookupBookings200ResponseBookingsInnerInstructor';

/**
 * The LookupBookings200ResponseBookingsInner model module.
 * @module model/LookupBookings200ResponseBookingsInner
 * @version 2.0.0
 */
class LookupBookings200ResponseBookingsInner {
    /**
     * Constructs a new <code>LookupBookings200ResponseBookingsInner</code>.
     * @alias module:model/LookupBookings200ResponseBookingsInner
     */
    constructor() { 
        
        LookupBookings200ResponseBookingsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LookupBookings200ResponseBookingsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LookupBookings200ResponseBookingsInner} obj Optional instance to populate.
     * @return {module:model/LookupBookings200ResponseBookingsInner} The populated <code>LookupBookings200ResponseBookingsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LookupBookings200ResponseBookingsInner();

            if (data.hasOwnProperty('bookingId')) {
                obj['bookingId'] = ApiClient.convertToType(data['bookingId'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = BookingStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('pickupLocation')) {
                obj['pickupLocation'] = ApiClient.convertToType(data['pickupLocation'], 'String');
            }
            if (data.hasOwnProperty('instructor')) {
                obj['instructor'] = LookupBookings200ResponseBookingsInnerInstructor.constructFromObject(data['instructor']);
            }
            if (data.hasOwnProperty('accountHolderName')) {
                obj['accountHolderName'] = ApiClient.convertToType(data['accountHolderName'], 'String');
            }
            if (data.hasOwnProperty('accountHolderPhone')) {
                obj['accountHolderPhone'] = ApiClient.convertToType(data['accountHolderPhone'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LookupBookings200ResponseBookingsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LookupBookings200ResponseBookingsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['bookingId'] && !(typeof data['bookingId'] === 'string' || data['bookingId'] instanceof String)) {
            throw new Error("Expected the field `bookingId` to be a primitive type in the JSON string but got " + data['bookingId']);
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['time'] && !(typeof data['time'] === 'string' || data['time'] instanceof String)) {
            throw new Error("Expected the field `time` to be a primitive type in the JSON string but got " + data['time']);
        }
        // ensure the json data is a string
        if (data['pickupLocation'] && !(typeof data['pickupLocation'] === 'string' || data['pickupLocation'] instanceof String)) {
            throw new Error("Expected the field `pickupLocation` to be a primitive type in the JSON string but got " + data['pickupLocation']);
        }
        // validate the optional field `instructor`
        if (data['instructor']) { // data not null
          LookupBookings200ResponseBookingsInnerInstructor.validateJSON(data['instructor']);
        }
        // ensure the json data is a string
        if (data['accountHolderName'] && !(typeof data['accountHolderName'] === 'string' || data['accountHolderName'] instanceof String)) {
            throw new Error("Expected the field `accountHolderName` to be a primitive type in the JSON string but got " + data['accountHolderName']);
        }
        // ensure the json data is a string
        if (data['accountHolderPhone'] && !(typeof data['accountHolderPhone'] === 'string' || data['accountHolderPhone'] instanceof String)) {
            throw new Error("Expected the field `accountHolderPhone` to be a primitive type in the JSON string but got " + data['accountHolderPhone']);
        }

        return true;
    }


}



/**
 * @member {String} bookingId
 */
LookupBookings200ResponseBookingsInner.prototype['bookingId'] = undefined;

/**
 * @member {String} date
 */
LookupBookings200ResponseBookingsInner.prototype['date'] = undefined;

/**
 * @member {String} time
 */
LookupBookings200ResponseBookingsInner.prototype['time'] = undefined;

/**
 * @member {module:model/BookingStatus} status
 */
LookupBookings200ResponseBookingsInner.prototype['status'] = undefined;

/**
 * @member {String} pickupLocation
 */
LookupBookings200ResponseBookingsInner.prototype['pickupLocation'] = undefined;

/**
 * @member {module:model/LookupBookings200ResponseBookingsInnerInstructor} instructor
 */
LookupBookings200ResponseBookingsInner.prototype['instructor'] = undefined;

/**
 * @member {String} accountHolderName
 */
LookupBookings200ResponseBookingsInner.prototype['accountHolderName'] = undefined;

/**
 * @member {String} accountHolderPhone
 */
LookupBookings200ResponseBookingsInner.prototype['accountHolderPhone'] = undefined;






export default LookupBookings200ResponseBookingsInner;

