/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OtpResponse model module.
 * @module model/OtpResponse
 * @version 2.0.0
 */
class OtpResponse {
    /**
     * Constructs a new <code>OtpResponse</code>.
     * @alias module:model/OtpResponse
     */
    constructor() { 
        
        OtpResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OtpResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OtpResponse} obj Optional instance to populate.
     * @return {module:model/OtpResponse} The populated <code>OtpResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OtpResponse();

            if (data.hasOwnProperty('verificationId')) {
                obj['verificationId'] = ApiClient.convertToType(data['verificationId'], 'String');
            }
            if (data.hasOwnProperty('delivery')) {
                obj['delivery'] = ApiClient.convertToType(data['delivery'], 'String');
            }
            if (data.hasOwnProperty('expiresIn')) {
                obj['expiresIn'] = ApiClient.convertToType(data['expiresIn'], 'Number');
            }
            if (data.hasOwnProperty('maxAttempts')) {
                obj['maxAttempts'] = ApiClient.convertToType(data['maxAttempts'], 'Number');
            }
            if (data.hasOwnProperty('resendAfterSeconds')) {
                obj['resendAfterSeconds'] = ApiClient.convertToType(data['resendAfterSeconds'], 'Number');
            }
            if (data.hasOwnProperty('rateLimitPerHour')) {
                obj['rateLimitPerHour'] = ApiClient.convertToType(data['rateLimitPerHour'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OtpResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OtpResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['verificationId'] && !(typeof data['verificationId'] === 'string' || data['verificationId'] instanceof String)) {
            throw new Error("Expected the field `verificationId` to be a primitive type in the JSON string but got " + data['verificationId']);
        }
        // ensure the json data is a string
        if (data['delivery'] && !(typeof data['delivery'] === 'string' || data['delivery'] instanceof String)) {
            throw new Error("Expected the field `delivery` to be a primitive type in the JSON string but got " + data['delivery']);
        }

        return true;
    }


}



/**
 * @member {String} verificationId
 */
OtpResponse.prototype['verificationId'] = undefined;

/**
 * @member {String} delivery
 */
OtpResponse.prototype['delivery'] = undefined;

/**
 * @member {Number} expiresIn
 */
OtpResponse.prototype['expiresIn'] = undefined;

/**
 * @member {Number} maxAttempts
 */
OtpResponse.prototype['maxAttempts'] = undefined;

/**
 * @member {Number} resendAfterSeconds
 */
OtpResponse.prototype['resendAfterSeconds'] = undefined;

/**
 * @member {Number} rateLimitPerHour
 */
OtpResponse.prototype['rateLimitPerHour'] = undefined;






export default OtpResponse;

