/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RescheduleBooking200Response model module.
 * @module model/RescheduleBooking200Response
 * @version 2.0.0
 */
class RescheduleBooking200Response {
    /**
     * Constructs a new <code>RescheduleBooking200Response</code>.
     * @alias module:model/RescheduleBooking200Response
     */
    constructor() { 
        
        RescheduleBooking200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RescheduleBooking200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RescheduleBooking200Response} obj Optional instance to populate.
     * @return {module:model/RescheduleBooking200Response} The populated <code>RescheduleBooking200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RescheduleBooking200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('bookingId')) {
                obj['bookingId'] = ApiClient.convertToType(data['bookingId'], 'String');
            }
            if (data.hasOwnProperty('newDate')) {
                obj['newDate'] = ApiClient.convertToType(data['newDate'], 'String');
            }
            if (data.hasOwnProperty('newTime')) {
                obj['newTime'] = ApiClient.convertToType(data['newTime'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RescheduleBooking200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RescheduleBooking200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['bookingId'] && !(typeof data['bookingId'] === 'string' || data['bookingId'] instanceof String)) {
            throw new Error("Expected the field `bookingId` to be a primitive type in the JSON string but got " + data['bookingId']);
        }
        // ensure the json data is a string
        if (data['newDate'] && !(typeof data['newDate'] === 'string' || data['newDate'] instanceof String)) {
            throw new Error("Expected the field `newDate` to be a primitive type in the JSON string but got " + data['newDate']);
        }
        // ensure the json data is a string
        if (data['newTime'] && !(typeof data['newTime'] === 'string' || data['newTime'] instanceof String)) {
            throw new Error("Expected the field `newTime` to be a primitive type in the JSON string but got " + data['newTime']);
        }

        return true;
    }


}



/**
 * @member {Boolean} success
 */
RescheduleBooking200Response.prototype['success'] = undefined;

/**
 * @member {String} bookingId
 */
RescheduleBooking200Response.prototype['bookingId'] = undefined;

/**
 * @member {String} newDate
 */
RescheduleBooking200Response.prototype['newDate'] = undefined;

/**
 * @member {String} newTime
 */
RescheduleBooking200Response.prototype['newTime'] = undefined;






export default RescheduleBooking200Response;

