/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Instructor from './Instructor';
import SearchInstructorsByLocation200ResponseSearchLocation from './SearchInstructorsByLocation200ResponseSearchLocation';

/**
 * The SearchInstructorsByLocation200Response model module.
 * @module model/SearchInstructorsByLocation200Response
 * @version 2.0.0
 */
class SearchInstructorsByLocation200Response {
    /**
     * Constructs a new <code>SearchInstructorsByLocation200Response</code>.
     * @alias module:model/SearchInstructorsByLocation200Response
     */
    constructor() { 
        
        SearchInstructorsByLocation200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchInstructorsByLocation200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchInstructorsByLocation200Response} obj Optional instance to populate.
     * @return {module:model/SearchInstructorsByLocation200Response} The populated <code>SearchInstructorsByLocation200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchInstructorsByLocation200Response();

            if (data.hasOwnProperty('instructors')) {
                obj['instructors'] = ApiClient.convertToType(data['instructors'], [Instructor]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('searchLocation')) {
                obj['searchLocation'] = SearchInstructorsByLocation200ResponseSearchLocation.constructFromObject(data['searchLocation']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchInstructorsByLocation200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchInstructorsByLocation200Response</code>.
     */
    static validateJSON(data) {
        if (data['instructors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['instructors'])) {
                throw new Error("Expected the field `instructors` to be an array in the JSON data but got " + data['instructors']);
            }
            // validate the optional field `instructors` (array)
            for (const item of data['instructors']) {
                Instructor.validateJSON(item);
            };
        }
        // validate the optional field `searchLocation`
        if (data['searchLocation']) { // data not null
          SearchInstructorsByLocation200ResponseSearchLocation.validateJSON(data['searchLocation']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Instructor>} instructors
 */
SearchInstructorsByLocation200Response.prototype['instructors'] = undefined;

/**
 * @member {Number} count
 */
SearchInstructorsByLocation200Response.prototype['count'] = undefined;

/**
 * @member {module:model/SearchInstructorsByLocation200ResponseSearchLocation} searchLocation
 */
SearchInstructorsByLocation200Response.prototype['searchLocation'] = undefined;






export default SearchInstructorsByLocation200Response;

