/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendOtp200Response model module.
 * @module model/SendOtp200Response
 * @version 2.0.0
 */
class SendOtp200Response {
    /**
     * Constructs a new <code>SendOtp200Response</code>.
     * @alias module:model/SendOtp200Response
     */
    constructor() { 
        
        SendOtp200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendOtp200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendOtp200Response} obj Optional instance to populate.
     * @return {module:model/SendOtp200Response} The populated <code>SendOtp200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendOtp200Response();

            if (data.hasOwnProperty('verificationId')) {
                obj['verificationId'] = ApiClient.convertToType(data['verificationId'], 'String');
            }
            if (data.hasOwnProperty('delivery')) {
                obj['delivery'] = ApiClient.convertToType(data['delivery'], 'String');
            }
            if (data.hasOwnProperty('expiresIn')) {
                obj['expiresIn'] = ApiClient.convertToType(data['expiresIn'], 'Number');
            }
            if (data.hasOwnProperty('maxAttempts')) {
                obj['maxAttempts'] = ApiClient.convertToType(data['maxAttempts'], 'Number');
            }
            if (data.hasOwnProperty('resendAfterSeconds')) {
                obj['resendAfterSeconds'] = ApiClient.convertToType(data['resendAfterSeconds'], 'Number');
            }
            if (data.hasOwnProperty('rateLimitPerHour')) {
                obj['rateLimitPerHour'] = ApiClient.convertToType(data['rateLimitPerHour'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SendOtp200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SendOtp200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['verificationId'] && !(typeof data['verificationId'] === 'string' || data['verificationId'] instanceof String)) {
            throw new Error("Expected the field `verificationId` to be a primitive type in the JSON string but got " + data['verificationId']);
        }
        // ensure the json data is a string
        if (data['delivery'] && !(typeof data['delivery'] === 'string' || data['delivery'] instanceof String)) {
            throw new Error("Expected the field `delivery` to be a primitive type in the JSON string but got " + data['delivery']);
        }

        return true;
    }


}



/**
 * @member {String} verificationId
 */
SendOtp200Response.prototype['verificationId'] = undefined;

/**
 * delivery method used (sms|email)
 * @member {String} delivery
 */
SendOtp200Response.prototype['delivery'] = undefined;

/**
 * seconds until OTP expires (typically 300)
 * @member {Number} expiresIn
 */
SendOtp200Response.prototype['expiresIn'] = undefined;

/**
 * Maximum number of confirmation attempts allowed for this verification (typically 3)
 * @member {Number} maxAttempts
 */
SendOtp200Response.prototype['maxAttempts'] = undefined;

/**
 * Seconds until a new OTP can be requested (typically 60)
 * @member {Number} resendAfterSeconds
 */
SendOtp200Response.prototype['resendAfterSeconds'] = undefined;

/**
 * Number of OTP requests allowed per hour for the caller (typically 3)
 * @member {Number} rateLimitPerHour
 */
SendOtp200Response.prototype['rateLimitPerHour'] = undefined;






export default SendOtp200Response;

