/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendOtpRequest model module.
 * @module model/SendOtpRequest
 * @version 2.0.0
 */
class SendOtpRequest {
    /**
     * Constructs a new <code>SendOtpRequest</code>.
     * @alias module:model/SendOtpRequest
     * @param purpose {module:model/SendOtpRequest.PurposeEnum} Purpose for verification; used for auditing and expiry.
     */
    constructor(purpose) { 
        
        SendOtpRequest.initialize(this, purpose);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, purpose) { 
        obj['purpose'] = purpose;
    }

    /**
     * Constructs a <code>SendOtpRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendOtpRequest} obj Optional instance to populate.
     * @return {module:model/SendOtpRequest} The populated <code>SendOtpRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendOtpRequest();

            if (data.hasOwnProperty('purpose')) {
                obj['purpose'] = ApiClient.convertToType(data['purpose'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('ttlSeconds')) {
                obj['ttlSeconds'] = ApiClient.convertToType(data['ttlSeconds'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SendOtpRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SendOtpRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SendOtpRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['purpose'] && !(typeof data['purpose'] === 'string' || data['purpose'] instanceof String)) {
            throw new Error("Expected the field `purpose` to be a primitive type in the JSON string but got " + data['purpose']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}

SendOtpRequest.RequiredProperties = ["purpose"];

/**
 * Purpose for verification; used for auditing and expiry.
 * @member {module:model/SendOtpRequest.PurposeEnum} purpose
 */
SendOtpRequest.prototype['purpose'] = undefined;

/**
 * Phone number to send SMS OTP to
 * @member {String} phone
 */
SendOtpRequest.prototype['phone'] = undefined;

/**
 * Email to send OTP to (alternative to phone)
 * @member {String} email
 */
SendOtpRequest.prototype['email'] = undefined;

/**
 * Optional desired TTL for the OTP in seconds (backend may enforce limits)
 * @member {Number} ttlSeconds
 */
SendOtpRequest.prototype['ttlSeconds'] = undefined;





/**
 * Allowed values for the <code>purpose</code> property.
 * @enum {String}
 * @readonly
 */
SendOtpRequest['PurposeEnum'] = {

    /**
     * value: "reschedule"
     * @const
     */
    "reschedule": "reschedule",

    /**
     * value: "cancel"
     * @const
     */
    "cancel": "cancel",

    /**
     * value: "login"
     * @const
     */
    "login": "login"
};



export default SendOtpRequest;

