/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValidateLocation200ResponseComponents model module.
 * @module model/ValidateLocation200ResponseComponents
 * @version 2.0.0
 */
class ValidateLocation200ResponseComponents {
    /**
     * Constructs a new <code>ValidateLocation200ResponseComponents</code>.
     * @alias module:model/ValidateLocation200ResponseComponents
     */
    constructor() { 
        
        ValidateLocation200ResponseComponents.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidateLocation200ResponseComponents</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidateLocation200ResponseComponents} obj Optional instance to populate.
     * @return {module:model/ValidateLocation200ResponseComponents} The populated <code>ValidateLocation200ResponseComponents</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidateLocation200ResponseComponents();

            if (data.hasOwnProperty('suburb')) {
                obj['suburb'] = ApiClient.convertToType(data['suburb'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('postcode')) {
                obj['postcode'] = ApiClient.convertToType(data['postcode'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidateLocation200ResponseComponents</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidateLocation200ResponseComponents</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['suburb'] && !(typeof data['suburb'] === 'string' || data['suburb'] instanceof String)) {
            throw new Error("Expected the field `suburb` to be a primitive type in the JSON string but got " + data['suburb']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['postcode'] && !(typeof data['postcode'] === 'string' || data['postcode'] instanceof String)) {
            throw new Error("Expected the field `postcode` to be a primitive type in the JSON string but got " + data['postcode']);
        }

        return true;
    }


}



/**
 * @member {String} suburb
 */
ValidateLocation200ResponseComponents.prototype['suburb'] = undefined;

/**
 * @member {String} state
 */
ValidateLocation200ResponseComponents.prototype['state'] = undefined;

/**
 * @member {String} postcode
 */
ValidateLocation200ResponseComponents.prototype['postcode'] = undefined;






export default ValidateLocation200ResponseComponents;

