/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ValidateLocation200ResponseComponents from './ValidateLocation200ResponseComponents';

/**
 * The ValidateLocation200Response model module.
 * @module model/ValidateLocation200Response
 * @version 2.0.0
 */
class ValidateLocation200Response {
    /**
     * Constructs a new <code>ValidateLocation200Response</code>.
     * @alias module:model/ValidateLocation200Response
     */
    constructor() { 
        
        ValidateLocation200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidateLocation200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidateLocation200Response} obj Optional instance to populate.
     * @return {module:model/ValidateLocation200Response} The populated <code>ValidateLocation200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidateLocation200Response();

            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('formattedAddress')) {
                obj['formattedAddress'] = ApiClient.convertToType(data['formattedAddress'], 'String');
            }
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
            }
            if (data.hasOwnProperty('components')) {
                obj['components'] = ValidateLocation200ResponseComponents.constructFromObject(data['components']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('suggestions')) {
                obj['suggestions'] = ApiClient.convertToType(data['suggestions'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidateLocation200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidateLocation200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['formattedAddress'] && !(typeof data['formattedAddress'] === 'string' || data['formattedAddress'] instanceof String)) {
            throw new Error("Expected the field `formattedAddress` to be a primitive type in the JSON string but got " + data['formattedAddress']);
        }
        // validate the optional field `components`
        if (data['components']) { // data not null
          ValidateLocation200ResponseComponents.validateJSON(data['components']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['suggestions'])) {
            throw new Error("Expected the field `suggestions` to be an array in the JSON data but got " + data['suggestions']);
        }

        return true;
    }


}



/**
 * @member {Boolean} valid
 */
ValidateLocation200Response.prototype['valid'] = undefined;

/**
 * @member {String} formattedAddress
 */
ValidateLocation200Response.prototype['formattedAddress'] = undefined;

/**
 * @member {Number} lat
 */
ValidateLocation200Response.prototype['lat'] = undefined;

/**
 * @member {Number} lng
 */
ValidateLocation200Response.prototype['lng'] = undefined;

/**
 * @member {module:model/ValidateLocation200ResponseComponents} components
 */
ValidateLocation200Response.prototype['components'] = undefined;

/**
 * Present if valid is false
 * @member {String} error
 */
ValidateLocation200Response.prototype['error'] = undefined;

/**
 * Suggestions if location not found
 * @member {Array.<String>} suggestions
 */
ValidateLocation200Response.prototype['suggestions'] = undefined;






export default ValidateLocation200Response;

