/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DriveBookVoiceServiceApi);
  }
}(this, function(expect, DriveBookVoiceServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DriveBookVoiceServiceApi.Instructor();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Instructor', function() {
    it('should create an instance of Instructor', function() {
      // uncomment below and update the code to test Instructor
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be.a(DriveBookVoiceServiceApi.Instructor);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property hourlyRate (base name: "hourlyRate")', function() {
      // uncomment below and update the code to test the property hourlyRate
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property rating (base name: "rating")', function() {
      // uncomment below and update the code to test the property rating
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property reviews (base name: "reviews")', function() {
      // uncomment below and update the code to test the property reviews
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property bio (base name: "bio")', function() {
      // uncomment below and update the code to test the property bio
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property vehicleTypes (base name: "vehicleTypes")', function() {
      // uncomment below and update the code to test the property vehicleTypes
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property languages (base name: "languages")', function() {
      // uncomment below and update the code to test the property languages
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property profileImage (base name: "profileImage")', function() {
      // uncomment below and update the code to test the property profileImage
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property totalBookings (base name: "totalBookings")', function() {
      // uncomment below and update the code to test the property totalBookings
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property carMake (base name: "carMake")', function() {
      // uncomment below and update the code to test the property carMake
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property carModel (base name: "carModel")', function() {
      // uncomment below and update the code to test the property carModel
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property carYear (base name: "carYear")', function() {
      // uncomment below and update the code to test the property carYear
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new DriveBookVoiceServiceApi.Instructor();
      //expect(instance).to.be();
    });

  });

}));
