/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DriveBookVoiceServiceApi);
  }
}(this, function(expect, DriveBookVoiceServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DriveBookVoiceServiceApi.SendOtp200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SendOtp200Response', function() {
    it('should create an instance of SendOtp200Response', function() {
      // uncomment below and update the code to test SendOtp200Response
      //var instance = new DriveBookVoiceServiceApi.SendOtp200Response();
      //expect(instance).to.be.a(DriveBookVoiceServiceApi.SendOtp200Response);
    });

    it('should have the property verificationId (base name: "verificationId")', function() {
      // uncomment below and update the code to test the property verificationId
      //var instance = new DriveBookVoiceServiceApi.SendOtp200Response();
      //expect(instance).to.be();
    });

    it('should have the property delivery (base name: "delivery")', function() {
      // uncomment below and update the code to test the property delivery
      //var instance = new DriveBookVoiceServiceApi.SendOtp200Response();
      //expect(instance).to.be();
    });

    it('should have the property expiresIn (base name: "expiresIn")', function() {
      // uncomment below and update the code to test the property expiresIn
      //var instance = new DriveBookVoiceServiceApi.SendOtp200Response();
      //expect(instance).to.be();
    });

    it('should have the property maxAttempts (base name: "maxAttempts")', function() {
      // uncomment below and update the code to test the property maxAttempts
      //var instance = new DriveBookVoiceServiceApi.SendOtp200Response();
      //expect(instance).to.be();
    });

    it('should have the property resendAfterSeconds (base name: "resendAfterSeconds")', function() {
      // uncomment below and update the code to test the property resendAfterSeconds
      //var instance = new DriveBookVoiceServiceApi.SendOtp200Response();
      //expect(instance).to.be();
    });

    it('should have the property rateLimitPerHour (base name: "rateLimitPerHour")', function() {
      // uncomment below and update the code to test the property rateLimitPerHour
      //var instance = new DriveBookVoiceServiceApi.SendOtp200Response();
      //expect(instance).to.be();
    });

  });

}));
