/**
 * DriveBook Voice Service API
 * API for AI voice agent to interact with DriveBook platform for booking driving lessons. The hybrid voice service exposes these `/api/_*` endpoints and proxies them to the main DriveBook application.  RECOMMENDED AI CONVERSATION FLOW (OPTIMIZED): 1. Ask user for pickup location 2. Validate location via /locations/validate 3. Get smart recommendations via /instructors/recommendations (AI-ranked, top 3) 4. Present options: \"I found 3 great instructors: Debesay (top rated), Michael (best value), Sarah (closest)\" 5. User selects instructor 6. Call /availability/slots to check times 7. Call /packages to present package options with savings 8. Create booking via /public/bookings/bulk (backend calculates pricing, generates password)  KEY IMPROVEMENTS: - AI does NOT ask for password (backend generates secure password automatically) 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DriveBookVoiceServiceApi);
  }
}(this, function(expect, DriveBookVoiceServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DriveBookVoiceServiceApi.ValidateLocation200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ValidateLocation200Response', function() {
    it('should create an instance of ValidateLocation200Response', function() {
      // uncomment below and update the code to test ValidateLocation200Response
      //var instance = new DriveBookVoiceServiceApi.ValidateLocation200Response();
      //expect(instance).to.be.a(DriveBookVoiceServiceApi.ValidateLocation200Response);
    });

    it('should have the property valid (base name: "valid")', function() {
      // uncomment below and update the code to test the property valid
      //var instance = new DriveBookVoiceServiceApi.ValidateLocation200Response();
      //expect(instance).to.be();
    });

    it('should have the property formattedAddress (base name: "formattedAddress")', function() {
      // uncomment below and update the code to test the property formattedAddress
      //var instance = new DriveBookVoiceServiceApi.ValidateLocation200Response();
      //expect(instance).to.be();
    });

    it('should have the property lat (base name: "lat")', function() {
      // uncomment below and update the code to test the property lat
      //var instance = new DriveBookVoiceServiceApi.ValidateLocation200Response();
      //expect(instance).to.be();
    });

    it('should have the property lng (base name: "lng")', function() {
      // uncomment below and update the code to test the property lng
      //var instance = new DriveBookVoiceServiceApi.ValidateLocation200Response();
      //expect(instance).to.be();
    });

    it('should have the property components (base name: "components")', function() {
      // uncomment below and update the code to test the property components
      //var instance = new DriveBookVoiceServiceApi.ValidateLocation200Response();
      //expect(instance).to.be();
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instance = new DriveBookVoiceServiceApi.ValidateLocation200Response();
      //expect(instance).to.be();
    });

    it('should have the property suggestions (base name: "suggestions")', function() {
      // uncomment below and update the code to test the property suggestions
      //var instance = new DriveBookVoiceServiceApi.ValidateLocation200Response();
      //expect(instance).to.be();
    });

  });

}));
